# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fpldata',
            options={'ordering': ['import_date'], 'verbose_name': 'FPL Data', 'verbose_name_plural': 'FPL Data'},
        ),
        migrations.AlterField(
            model_name='fpldata',
            name='data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
