# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0003_auto_20190811_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
