# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0005_auto_20190825_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fplcornerapp.Season'),
        ),
    ]
