# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-05 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0006_fixture_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture_stat',
            name='stat_name',
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='bps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='clean_sheets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='cost_change_event',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='cost_change_event_fall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='cost_change_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='cost_change_start_fall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='creativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='ep_next',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='ep_this',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='form',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='goals_conceded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='goals_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='ict_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='influence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='now_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='points_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='red_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='saves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='selected_by_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='threat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='transfers_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='transfers_in_event',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='transfers_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='transfers_out_event',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='value_form',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='value_season',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture_stat',
            name='yellow_cards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
