# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0007_auto_20190905_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixture_Stat',
            new_name='Player_Fixture_Stat',
        ),
        migrations.AlterModelOptions(
            name='player_fixture_stat',
            options={'ordering': ['fixture'], 'verbose_name': 'Player Fixture_Stat', 'verbose_name_plural': 'Player Fixture_Stats'},
        ),
    ]
