# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-09-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0008_auto_20190905_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
