# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-09-15 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0009_event_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='code',
        ),
    ]
