# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-10-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0010_remove_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Weekly_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.FloatField(blank=True, null=True)),
                ('goals_scored', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('clean_sheets', models.IntegerField(blank=True, null=True)),
                ('goals_conceded', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('influence', models.FloatField(blank=True, null=True)),
                ('creativity', models.FloatField(blank=True, null=True)),
                ('threat', models.FloatField(blank=True, null=True)),
                ('ict_index', models.FloatField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fplcornerapp.Fixture')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fplcornerapp.Player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fplcornerapp.Season')),
            ],
            options={
                'ordering': ['fixture'],
            },
        ),
    ]
