# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-10-09 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0011_player_weekly_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_fixture_stat',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='player_fixture_stat',
            name='player',
        ),
        migrations.DeleteModel(
            name='Player_Fixture_Stat',
        ),
    ]
