# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-01-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0013_player_last_six_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_last_six_stat',
            name='limited_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player_last_six_stat',
            name='total_games',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
