# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-01-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fplcornerapp', '0014_auto_20210104_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_last_six_stat',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fplcornerapp.Season'),
        ),
    ]
